### ISSUE TITLE
FR: zero-length CircularQueue

### ISSUE THREAD

**Issue by vi** [YaLTeR/circular-queue#4]
`len` should return `0`, `is_empty` should return `true`, `capacity` should return `0`, `clear` and `push` should do nothing, iterators should be empty.

Can it be done by just removing [the panic](https://docs.rs/circular-queue/0.2.3/src/circular_queue/lib.rs.html#89) and adding a check to `push` instead?

**Comment by YaLTeR** [comment]
Sure, that makes sense.
