### ISSUE TITLE
Add serde support

### ISSUE THREAD

**Issue by ghost** [YaLTeR/circular-queue#6]
I think it would be very useful to have serialization/deserialization support (behind a feature, probably) for circular queues.  If you are interested, I can give the implementation a shot and submit it on a pull request.

**Comment by YaLTeR** [comment]
Sure, would be great behind a feature.

**Comment by entropylost** [comment]
According to the documentation this has already be done, right?

**Comment by ghost** [comment]
Yes - sorry.  It was merged a while ago.  Closing the issue.
